  0%|                                                                                                                                                         | 0/1075776 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ubuntu/research/recursive_char_prediction/train.py", line 56, in <module>
    torch.save(rnn.state_dict(), f"output/{epoch}_{i}_model.pth")
  File "/home/ubuntu/anaconda3/envs/cvpr/lib/python3.10/site-packages/torch/serialization.py", line 440, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/home/ubuntu/anaconda3/envs/cvpr/lib/python3.10/site-packages/torch/serialization.py", line 315, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/home/ubuntu/anaconda3/envs/cvpr/lib/python3.10/site-packages/torch/serialization.py", line 288, in __init__
    super().__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory output does not exist.
Traceback (most recent call last):
  File "/home/ubuntu/research/recursive_char_prediction/train.py", line 56, in <module>
    torch.save(rnn.state_dict(), f"output/{epoch}_{i}_model.pth")
  File "/home/ubuntu/anaconda3/envs/cvpr/lib/python3.10/site-packages/torch/serialization.py", line 440, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/home/ubuntu/anaconda3/envs/cvpr/lib/python3.10/site-packages/torch/serialization.py", line 315, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/home/ubuntu/anaconda3/envs/cvpr/lib/python3.10/site-packages/torch/serialization.py", line 288, in __init__
    super().__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory output does not exist.
Epoch: 0, Loss: 4.792358875274658