  0%|                                                                                                                                                                                                                                                         | 0/1075776 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/hsy/Documents/Study/ESE5460/hw3/train.py", line 42, in <module>
    output, _ = rnn(x) # (batch_size, seq_length, vocab_size)
                ^^^^^^
  File "/Users/hsy/anaconda3/anaconda3/envs/torch/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hsy/anaconda3/anaconda3/envs/torch/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hsy/Documents/Study/ESE5460/hw3/model/rnn.py", line 18, in forward
    output, hidden = self.rnn_block(input, hidden)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hsy/anaconda3/anaconda3/envs/torch/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hsy/anaconda3/anaconda3/envs/torch/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hsy/anaconda3/anaconda3/envs/torch/lib/python3.12/site-packages/torch/nn/modules/rnn.py", line 714, in forward
    result = _VF.rnn_tanh(
             ^^^^^^^^^^^^^
RuntimeError: Input and hidden tensors are not at the same device, found input tensor at mps:0 and hidden tensor at cpu
